export const products: Product[] = [
  {
    id: 1,
    title: 'Summer',
    gender: 'Women',
    category: 'Blouses',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/Blouse.jpeg'),
    color1: '#000000',
    color2: '#A44692',
    color3: '#A68A44',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  {
    id: 2,
    title: 'Casual',
    gender: 'Women',
    category: 'Tops',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/Casual.jpg'),
    color1: '#000000',
    color2: '#A68A44',
    color3: '#6627C3',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  {
    id: 3,
    title: 'Collar',
    gender: 'Women',
    category: 'Blouse',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/Colar.jpg'),
    color1: '#F0DAC2',
    color2: '#936847',
    color3: '#008000',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  {
    id: 4,
    title: 'Classic',
    gender: 'Men',
    category: 'Blazers',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/Blazers.jpg'),
    color1: '#DFB07D',
    color2: '#008000',
    color3: '#4230CA',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  {
    id: 5,
    title: 'Short',
    gender: 'Women',
    category: 'Dresses',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/dress.jpeg'),
    color1: '#000000',
    color2: '#1A7458',
    color3: '#3489D0',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  {
    id: 6,
    title: 'Summer',
    gender: 'Women',
    category: 'Tops',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/greenTop.jpg'),
    color1: '#000000',
    color2: '#936847',
    color3: '#43682A',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  {
    id: 7,
    title: 'Classic',
    gender: 'Women',
    category: 'Blouse',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/GreenBl.jpg'),
    color1: '#43682A',
    color2: '#E4B644',
    color3: '#008000',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  {
    id: 8,
    title: 'Winter',
    gender: 'Kids',
    category: 'Hoodie',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/hoodie.jpg'),
    color1: '#000000',
    color2: '#936847',
    color3: '#008000',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  {
    id: 9,
    title: 'Set',
    gender: 'Women',
    category: 'Sweaters',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/ss.jpg'),
    color1: '#000000',
    color2: '#936847',
    color3: '#008000',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
];
