export const productDis: Product[] = [
  {
    id: 1,
    title: 'Long Sleeves',
    gender: 'Women',
    category: 'Blouses',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/Blouse.jpeg'),
    color1: '#000000',
    color2: '#A44692',
    color3: '#A68A44',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  {
    id: 2,
    title: 'Casual',
    gender: 'Women',
    category: 'Tops',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/Casual.jpg'),
    color1: '#000000',
    color2: '#A68A44',
    color3: '#6627C3',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  {
    id: 3,
    title: 'Collar',
    gender: 'Women',
    category: 'Blouse',
    price: 19.99,
    priceDiscount: 9.99,
    imagePath: require('../../img/Colar.jpg'),
    color1: '#F0DAC2',
    color2: '#936847',
    color3: '#008000',
    size1: 'S',
    size2: 'M',
    size3: 'L',
  },
  ];
  